name: ET WEB CI

on:
  push:
    branches:
      - main
      - dev
      - stag 
  workflow_dispatch:

 
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Deploy to Hetzner Server via SSH action
        uses: appleboy/ssh-action@master
        with:
          host: 157.90.240.27
          username: root
          key: ${{ secrets.PRIVATE_KEY }}
          port: 22
          script: |
            ls
            cp . /root/eltrm/et-web
  