name: ET WEB CI

on:
  push:
    branches:
      - main
      - dev
      - stag-* 
  workflow_dispatch:

 
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: copy file via ssh password
        uses: appleboy/scp-action@master
        with:
          host: 157.90.240.27
          username: root
          password: ${{ secrets.PASSWORD }}
          key: ${{ secrets.PRIVATE_KEY }}
          port: 22
          source: "./*"
          target: "/root/eltrm/et-web"            